package uz.zero.auth.enums


enum class ErrorCode(val code: Int) {
    VALIDATION_ERROR(40),
    ROLE_KEY_ALREADY_EXISTS(100),
    PERMISSION_GROUP_NOT_FOUND(101),
    ROLE_NOT_FOUND(102),
    ROLE_HAS_RELATION_WITH_USER(103),
    ROLE_LEVEL_BIGGER_THAN_YOURS(107),
    PHONE_NUMBER_ALREADY_EXISTS(108),
    PASSWORD_MISMATCH(120),
    USER_NOT_FOUND(109),

    INVALID_PASSWORD(110),

    INVALID_CREDENTIALS(111)
}